alias ls='ls -G'
alias l='ls -lA'
alias g='grep -I'
#alias e='emacs -nw'
alias llrt='ls -lrt'
alias llrtt='ls -lrt --color=always | tail'
alias f='find . -name'
alias t='git'
alias subl='/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl'
alias e='subl -w'
