#unalias -a
alias ls='ls -G --color=auto'
alias l='ls -lA'
alias g='grep -I'
alias e='subl'
alias llrt='ls -lrt'
alias llrtt='ls -lrt --color=always | tail'
alias lt='ls -lrt --color=always | tail'
#alias f='find . -name'
#alias t='git'
alias mp='/Applications/MPlayer\ OSX\ Extended.app/Contents/Resources/Binaries/mpextended.mpBinaries/Contents/MacOS/mplayer -fs'
alias gr='gradle'
# for grep-like highlight of match without suppressing the non-matching lines
alias h='ack --color-match="bold red" --passthru'
alias adbl='adb logcat -c & adb logcat'
alias adblg='adb logcat -c & adb logcat | grep "Exception$\|Error$\|Exception: \|Error: \|: 	at \|: 	Caused by: \|: 	\.\.\.\|\*\*\*\*\*"'
alias au='adb uninstall com.prezi.android'
alias mvn='mvn-color'
#alias m='mvn-color'
alias jl='jar tvf'
alias reload='if [[ "$SHELL" == "/bin/zsh" ]] ; then . ~/.zshrc ; else . ~/.bash_profile ; fi'
alias jcat='unzip -p'
alias sep='printf "${FG_BLUE}${BG_CYAN}% $(( COLUMNS / 2 + 10 ))s% $(( COLUMNS - COLUMNS / 2 - 10 ))s${NO_COLOR}\n" "$(date +"%Y-%m-%d  %T")" ""'
alias sshhal='ssh robertfa@bitsofproof.com -p 22222'
alias tpom='t pull origin master'
alias proto250='brew unlink protobuf && brew link protobuf250'
alias proto3='brew unlink protobuf250 && brew link protobuf'
alias grep='grep --color=auto'
alias o='xdg-open'
alias psql_start='sudo -u postgres psql -P pager=off postgres'
alias cdr='cd ~/work/repos/DACH-NY/_ref_apps/'
alias cds='cd ~/work/repos/DACH-NY/solution-spider'
# alias make='echo "${FG_CYAN}${BG_LIGHT_GREY}    Started at: "$(date +%H:%M:%S)"    ${NO_COLOR}" ; /usr/bin/time -f "${FG_BLUE}${BG_LIGHT_GREY}    Execution time: %E    ${NO_COLOR}" make'
alias da='/usr/bin/time -f "${FG_BLUE}${BG_LIGHT_GREY}    Execution time: %E    ${NO_COLOR}" da'
# runs FT for the provided tags, e.g. runft @SPD-1234
alias runft='make clean-logs-dir stop-application clean-app-nanobots run-ft ftracing=on fignore=@ignore ftags='
# open all error egress xmls from a FT in an editor
alias errs='for f in $(find logs/func-test/Functional/ -name *comm-808*.xml) ; do echo $f ; e $f ; done'
# opens all ingress xmls from a FT in an editor 
alias ei='e $(find logs -name "*.xml" | grep Ingress)'
# opens all egress xmls from a FT in an editor 
alias ee='e $(find logs -name "*.xml" | grep Egress)'
alias agd='ag -G "\.daml$" "$@"'
alias ags='ag -G "\.scala$" "$@"'
alias agf='ag -G "\.feature$" "$@"'
alias agx='ag -G "\.xml$" "$@"'
alias damltest='echo "${FG_CYAN}${BG_LIGHT_GREY}    Started at: "$(date +%H:%M:%S)"    ${NO_COLOR}" ; /usr/bin/time -f "${FG_BLUE}${BG_LIGHT_GREY}    Execution time: %E    ${NO_COLOR}" daml damlc test --project-root /home/robert/work/repos/DACH-NY/solution-spider --files app/daml-model/src/DA/ASX/Test/BizProcess/Transfer/ParticipantToIssuer/Service.daml'
alias lmsimple='f *.xml | cut -f2 -d: | sort -t/ -k3'
# alias lm='f *.xml | cut -f2 -d: | sort -t/ -k3 | cat -b | sed -e "s/\(^ *[0-9]*\)\(.*\)/\1\2\1/" | grep "^ *[0-9]*\|[0-9]*$\|[a-z]\+-[0-9]*"'
alias mouse='sudo modprobe -r psmouse && sudo modprobe psmouse'