#unalias -a
alias ls='ls -G'
alias l='ls -lA'
alias g='grep -I'
#alias e='emacs -nw'
alias llrt='ls -lrt'
alias llrtt='ls -lrt | tail'
alias lt='ls -lrt | tail'
#alias f='find . -name'
#alias t='git'
alias subl='/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl'
alias e='subl'
alias mp='/Applications/MPlayer\ OSX\ Extended.app/Contents/Resources/Binaries/mpextended.mpBinaries/Contents/MacOS/mplayer -fs'
alias gr='gradle'
# for grep-like highlight of match without suppressing the non-matching lines
alias h='ack --color-match="bold red" --passthru'
alias adbl='adb logcat -c & adb logcat'
alias adblg='adb logcat -c & adb logcat | grep "Exception$\|Error$\|Exception: \|Error: \|: 	at \|: 	Caused by: \|: 	\.\.\.\|\*\*\*\*\*"'
alias au='adb uninstall com.prezi.android'
alias mvn='mvn-color'
#alias m='mvn-color'
alias jl='jar tvf'
alias reload='if [[ "$SHELL" == "/bin/zsh" ]] ; then . ~/.zshrc ; else . ~/.bash_profile ; fi'
alias jcat='unzip -p'
alias sep='printf "${FG_BLUE}${BG_CYAN}% $(( COLUMNS / 2 + 10 ))s% $(( COLUMNS - COLUMNS / 2 - 10 ))s${NO_COLOR}\n" "$(date +"%Y-%m-%d  %T")" ""'
alias sshhal='ssh robertfa@bitsofproof.com -p 22222'
alias tpom='t pull origin master'